/* v1.3.0 - UI exclusiva de otros ingresos fijos. Jaimau se gestiona en su módulo propio. */
import { $, fmtMoney } from './01_consts_utils.js';
import * as Data from './02_data.js';

const WEEK=[['1','Lunes'],['2','Martes'],['3','Miércoles'],['4','Jueves'],['5','Viernes'],['6','Sábado'],['0','Domingo']];
const monthDays=(includeEnd=false)=>[...Array.from({length:31},(_,i)=>[String(i+1),String(i+1)]),...(includeEnd?[['fin_mes','Fin de mes']]:[])];
const options=(items,selected='')=>items.map(([v,t])=>`<option value="${v}" ${v===String(selected)?'selected':''}>${t}</option>`).join('');
const fechaPagoTexto=(f,p,index)=>f.frecuencia==='Semanal'?`Cada ${WEEK.find(x=>x[0]===String(p.diaSemana))?.[1]||'semana'}`:f.frecuencia==='Quincenal'?`${index===0?'1ª quincena':'2ª quincena'} · ${p.diaMes==='fin_mes'?'Fin de mes':`Día ${p.diaMes}`}`:`Día ${p.diaMes}`;
const esJaimau=f=>/\bjaimau\b/i.test(String(f?.nombre||''));
function isDueToday(p,f,now=new Date()){if(f.frecuencia==='Semanal')return now.getDay()===Number(p.diaSemana);if(p.diaMes==='fin_mes')return now.getDate()===new Date(now.getFullYear(),now.getMonth()+1,0).getDate();return now.getDate()===Number(p.diaMes);}
function paidThisMonth(f,p,now=new Date()){const periodo=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;return Data.getState().movimientos.some(x=>x.tipo==='ingreso'&&x.refId===f.id&&x.pagoId===p.id&&x.periodo===periodo);}

export function renderIncomeUI(){
 const s=Data.getState(),zone=$('zoneIngresoFijo');
 if(zone){const activos=s.ingresosFijos.filter(x=>x.activo&&!esJaimau(x));zone.innerHTML=activos.length?activos.map(f=>`<div style="padding:10px 0;border-bottom:1px solid #e2e8f0"><strong>${f.nombre}</strong><small style="display:block;color:var(--text-sec);margin:3px 0 7px">${f.frecuencia}</small>${(f.pagos||[]).map((p,i)=>{const cobrado=paidThisMonth(f,p),vence=isDueToday(p,f);return `<div style="display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:6px"><span style="font-size:.82rem">${fechaPagoTexto(f,p,i)}${p.ultimoCobro?`<br><small>Último: ${fmtMoney(p.ultimoCobro.monto)}</small>`:''}</span><button class="btn ${cobrado?'btn-outline':vence?'btn-warning':'btn-success'}" style="width:auto;white-space:nowrap" data-income-id="${f.id}" data-payment-id="${p.id}" ${cobrado?'disabled':''}>${cobrado?'✓ Registrado':vence?'⚠️ ¿Te pagaron?':'Registrar pago'}</button></div>`;}).join('')}</div>`).join(''):'<small style="color:var(--text-sec)">Sin otros ingresos fijos configurados.</small>';}
 const saldoBtn=$('btnConfigSaldo');if(saldoBtn){const configurado=s.parametros.saldoInicialConfigurado;saldoBtn.textContent=configurado?'🔒 Saldo gestionado':'💵 Declarar saldo inicial';saldoBtn.className=configurado?'btn btn-outline':'btn btn-primary';}
 if(!s.parametros.saldoInicialConfigurado&&document.body.dataset.page==='index'&&!document.getElementById('setupSaldoAviso')){const main=document.querySelector('main.container'),aviso=document.createElement('section');aviso.id='setupSaldoAviso';aviso.className='card';aviso.style.cssText='border-left:5px solid #d97706';aviso.innerHTML='<strong>💵 Falta tu saldo inicial</strong><p style="font-size:.85rem;margin:6px 0">Declara cuánto dinero tienes actualmente para que el saldo de caja empiece desde una base real.</p><a class="btn btn-primary" href="admin.html" style="display:block;text-align:center;text-decoration:none">Configurar saldo</a>';main?.prepend(aviso);}
}
function closeSetup(){document.getElementById('incomeSetupModal')?.remove();}
function drawFields(){const f=$('incomeFreq')?.value,box=$('incomeFields');if(!box)return;if(f==='Semanal')box.innerHTML=`<label>Día de pago</label><select id="incomeD1" class="input-control">${options(WEEK,'6')}</select>`;else if(f==='Quincenal')box.innerHTML=`<label>Primer día de pago</label><select id="incomeD1" class="input-control">${options(monthDays(false),'15')}</select><label>Segundo día de pago</label><select id="incomeD2" class="input-control">${options(monthDays(true),'fin_mes')}</select>`;else box.innerHTML=`<label>Día de pago</label><select id="incomeD1" class="input-control">${options(monthDays(false),'1')}</select>`;}
function openSetup(){closeSetup();const el=document.createElement('div');el.id='incomeSetupModal';el.className='modal-overlay';el.style.display='flex';el.innerHTML=`<div class="modal"><h3>Nuevo ingreso fijo</h3><p style="font-size:.82rem;color:var(--text-sec);margin:0 0 10px">Jaimau ya se administra por separado como trabajo principal.</p><label>Nombre / empresa</label><input id="incomeName" class="input-control" autocomplete="organization"><label>Frecuencia de pago</label><select id="incomeFreq" class="input-control"><option value="Semanal">Semanal</option><option value="Quincenal" selected>Quincenal</option><option value="Mensual">Mensual</option></select><div id="incomeFields"></div><div class="modal-actions"><button id="incomeCancel" class="btn btn-outline">Cancelar</button><button id="incomeSave" class="btn btn-primary">Guardar</button></div></div>`;document.body.append(el);drawFields();$('incomeFreq').onchange=drawFields;$('incomeCancel').onclick=closeSetup;$('incomeSave').onclick=()=>{try{Data.crearIngresoFijo({nombre:$('incomeName').value,frecuencia:$('incomeFreq').value,dia1:$('incomeD1')?.value,dia2:$('incomeD2')?.value});closeSetup();renderIncomeUI();}catch(e){alert(e.message==='INGRESO_JAIMAU_DUPLICADO'?'Jaimau ya tiene su módulo de pago quincenal.':e.message==='NOMBRE_INVALIDO'?'Escribe el nombre de la empresa.':'Revisa los datos del ingreso.');}};}
function closePayment(){document.getElementById('incomePaymentModal')?.remove();}
function openPayment(incomeId,paymentId){const f=Data.getState().ingresosFijos.find(x=>x.id===incomeId),p=f?.pagos?.find(x=>x.id===paymentId);if(!f||!p||esJaimau(f))return;closePayment();const el=document.createElement('div');el.id='incomePaymentModal';el.className='modal-overlay';el.style.display='flex';el.innerHTML=`<div class="modal"><h3>💵 Pago recibido</h3><p style="margin:0 0 12px;color:var(--text-sec)">${f.nombre}</p><label>¿Cuánto te pagaron?</label><input id="incomePaidAmount" class="input-control" type="number" inputmode="decimal" min="0" step="0.01" autofocus><div class="modal-actions"><button id="incomePaidCancel" class="btn btn-outline">Cancelar</button><button id="incomePaidSave" class="btn btn-primary">Ingresar monto</button></div></div>`;document.body.append(el);$('incomePaidCancel').onclick=closePayment;$('incomePaidSave').onclick=()=>{try{Data.registrarCobroFijo(incomeId,paymentId,$('incomePaidAmount').value);closePayment();renderIncomeUI();}catch(e){alert(e.message==='COBRO_DUPLICADO'?'Este pago ya fue registrado este mes.':e.message==='MONTO_INVALIDO'?'Ingresa el monto que recibiste.':'No se pudo registrar el pago.');}};setTimeout(()=>$('incomePaidAmount')?.focus(),50);}
export function initIncomeUI(){$('btnIngresoFijoNuevo')?.addEventListener('click',openSetup);document.addEventListener('click',e=>{const b=e.target.closest('[data-income-id]');if(!b||b.disabled)return;openPayment(b.dataset.incomeId,b.dataset.paymentId);});renderIncomeUI();}
