/* v2.0.0 - Firebase offline-first, por usuario y con conflictos explícitos. */
import { FIREBASE_SYNC } from './firebase-config.js';
import * as Data from './02_data.js';

const META_KEY='presupuesto_sync_meta_v1';
const DEVICE_KEY='presupuesto_device_id_v1';
let auth=null,db=null,firebase=null,currentUser=null,conflictRemote=null,syncing=false,syncTimer=null,observerTimer=null,observedHash=null,authReady=false;
const getDeviceId=()=>{let id=localStorage.getItem(DEVICE_KEY);if(!id){id=`dev-${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(DEVICE_KEY,id);}return id;};
const loadMeta=()=>{try{return {...{baseRevision:0,dirty:false,lastSync:null},...JSON.parse(localStorage.getItem(META_KEY)||'{}')}}catch{return {baseRevision:0,dirty:false,lastSync:null}}};
const saveMeta=m=>localStorage.setItem(META_KEY,JSON.stringify(m));
let meta=typeof localStorage!=='undefined'?loadMeta():{baseRevision:0,dirty:false,lastSync:null};

const clone=v=>JSON.parse(JSON.stringify(v));
const stateHash=()=>JSON.stringify(Data.getState());
const hasMeaningfulLocalData=()=>{const s=Data.getState();return ['turnos','movimientos','cargasCombustible','fondosCombustibleEmpresa','deudas','gastosFijosMensuales','ingresosFijos','workSources','accounts'].some(k=>Array.isArray(s?.[k])&&s[k].length>0)||Boolean(s?.profile?.onboarded)||Boolean(s?.parametros?.saldoInicialConfigurado)||Boolean(s?.parametros?.kmInicialConfigurado);};
const collectionMerge=(local=[],remote=[])=>{const map=new Map();for(const item of remote||[])if(item?.id)map.set(item.id,clone(item));for(const item of local||[])if(item?.id)map.set(item.id,clone(item));return [...map.values()];};
function mergeStates(local,remote){
  const merged={...clone(remote||{}),...clone(local||{})};
  for(const key of ['turnos','movimientos','cargasCombustible','fondosCombustibleEmpresa','deudas','gastosFijosMensuales','ingresosFijos','workSources','accounts','assets'])merged[key]=collectionMerge(local?.[key],remote?.[key]);
  merged.wallet=clone(local?.wallet||remote?.wallet||{});
  merged.parametros=clone(local?.parametros||remote?.parametros||{});
  merged.profile={...(remote?.profile||{}),...(local?.profile||{})};
  merged.categoriasPersonalizadas={...(remote?.categoriasPersonalizadas||{}),...(local?.categoriasPersonalizadas||{})};
  merged.business={
    ingredients:collectionMerge(local?.business?.ingredients,remote?.business?.ingredients),
    products:collectionMerge(local?.business?.products,remote?.business?.products),
    sales:collectionMerge(local?.business?.sales,remote?.business?.sales)
  };
  merged.activeActivity=local?.activeActivity||remote?.activeActivity||null;
  merged.turnoActivo=merged.activeActivity;
  return merged;
}

function setStatus(message,tone='neutral'){const el=document.getElementById('syncStatus');if(!el)return;el.textContent=message;el.dataset.tone=tone;}
export function renderSyncUI(){const card=document.getElementById('syncCard'),zone=document.getElementById('syncPanel');if(!zone)return;if(!FIREBASE_SYNC.enabled||!authReady){card?.classList.add('hidden');return;}if(currentUser&&!conflictRemote){card?.classList.add('hidden');zone.innerHTML='';return;}card?.classList.remove('hidden');if(currentUser&&conflictRemote){zone.innerHTML='<div class="sync-conflict"><strong>⚠️ Conflicto de sincronización</strong><p style="margin:6px 0 10px">Hay cambios distintos en este dispositivo y en la nube. Elige cuál conservar.</p><button id="btnUseCloud" class="btn btn-outline">Usar nube</button><button id="btnUseLocal" class="btn btn-outline" style="margin-top:7px">Conservar local</button><button id="btnMergeSync" class="btn btn-primary" style="margin-top:7px">Fusionar sin duplicar</button></div>';document.getElementById('btnUseCloud')?.addEventListener('click',resolveUseCloud);document.getElementById('btnUseLocal')?.addEventListener('click',resolveUseLocal);document.getElementById('btnMergeSync')?.addEventListener('click',resolveMerge);return;}zone.innerHTML='<div class="sync-state"><strong>☁️ Sincronización disponible</strong><p>Inicia sesión con Google para respaldar y sincronizar tus datos entre dispositivos.</p><p id="syncStatus" style="margin:6px 0 12px;color:var(--text-sec)" aria-live="polite">Listo para iniciar sesión.</p><button id="btnSyncLogin" class="btn btn-primary">Continuar con Google</button></div>';document.getElementById('btnSyncLogin')?.addEventListener('click',signIn);}
function showSyncError(error){console.error('Firebase sync:',error);const card=document.getElementById('syncCard'),zone=document.getElementById('syncPanel'),code=String(error?.code||'');let message='⚠️ No se pudo sincronizar.';if(code.includes('unauthorized-domain'))message='⚠️ El dominio de esta app no está autorizado en Firebase Authentication.';else if(code.includes('popup-blocked'))message='⚠️ El navegador bloqueó la ventana de Google. Permite ventanas emergentes e intenta otra vez.';else if(code.includes('popup-closed'))message='Inicio de sesión cancelado.';else if(code.includes('operation-not-allowed'))message='⚠️ El proveedor Google no está habilitado en Firebase.';else if(code.includes('network-request-failed'))message='⚠️ No se pudo contactar Firebase. Revisa tu conexión e intenta otra vez.';else if(code)message=`⚠️ Error de sincronización (${code}).`;card?.classList.remove('hidden');if(zone&&!document.getElementById('syncStatus'))zone.innerHTML='<div class="sync-state"><strong>☁️ Sincronización</strong><p id="syncStatus" style="margin:6px 0 0;color:var(--text-sec)" aria-live="polite"></p></div>';setStatus(message,'error');}
export function notifyLocalChange(){if(!FIREBASE_SYNC.enabled)return;observedHash=stateHash();meta={...meta,dirty:true};saveMeta(meta);if(currentUser&&navigator.onLine){clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncNow().catch(showSyncError),1400);}}

async function loadFirebase(){if(firebase)return firebase;const v=FIREBASE_SYNC.sdkVersion||'12.18.0';const [appMod,authMod,firestoreMod]=await Promise.all([import(`https://www.gstatic.com/firebasejs/${v}/firebase-app.js`),import(`https://www.gstatic.com/firebasejs/${v}/firebase-auth.js`),import(`https://www.gstatic.com/firebasejs/${v}/firebase-firestore.js`)]);const app=appMod.initializeApp(FIREBASE_SYNC.config);auth=authMod.getAuth(app);db=firestoreMod.getFirestore(app);firebase={...authMod,...firestoreMod};await authMod.setPersistence(auth,authMod.browserLocalPersistence);return firebase;}
async function signIn(){const button=document.getElementById('btnSyncLogin');try{if(button){button.disabled=true;button.textContent='Abriendo Google…';}setStatus('Abriendo acceso con Google…');const f=await loadFirebase(),provider=new f.GoogleAuthProvider(),result=await f.signInWithPopup(auth,provider);currentUser=result.user;authReady=true;renderSyncUI();if(navigator.onLine)await syncNow();}catch(e){showSyncError(e);if(button){button.disabled=false;button.textContent='Continuar con Google';}}}
const docRef=()=>firebase.doc(db,'users',currentUser.uid,'budget','state');
async function applyRemote(remote){Data.restaurar(JSON.stringify(remote.state));observedHash=stateHash();meta={...meta,baseRevision:Number(remote.revision)||0,dirty:false,lastSync:new Date().toISOString()};saveMeta(meta);conflictRemote=null;renderSyncUI();document.dispatchEvent(new CustomEvent('budget:remote-applied'));}
export async function syncNow({forceLocal=false}={}){if(!FIREBASE_SYNC.enabled||!currentUser||syncing||!navigator.onLine)return;const currentHash=stateHash();if(observedHash!==null&&currentHash!==observedHash){observedHash=currentHash;meta={...meta,dirty:true};saveMeta(meta);}syncing=true;try{const f=await loadFirebase(),ref=docRef();const result=await f.runTransaction(db,async tx=>{const snap=await tx.get(ref),remote=snap.exists()?snap.data():null,remoteRevision=Number(remote?.revision)||0;if(remote&&remoteRevision>meta.baseRevision&&!forceLocal){if(meta.dirty)return{kind:'conflict',remote};return{kind:'pull',remote};}const revision=Math.max(remoteRevision,Number(meta.baseRevision)||0)+1;tx.set(ref,{state:clone(Data.getState()),revision,updatedAt:new Date().toISOString(),deviceId:getDeviceId()});return{kind:'push',revision};});if(result.kind==='conflict'){conflictRemote=result.remote;renderSyncUI();return;}if(result.kind==='pull'){await applyRemote(result.remote);return;}observedHash=stateHash();meta={...meta,baseRevision:result.revision,dirty:false,lastSync:new Date().toISOString()};saveMeta(meta);conflictRemote=null;renderSyncUI();}finally{syncing=false;}}
async function resolveUseCloud(){if(!conflictRemote)return;await applyRemote(conflictRemote);}async function resolveUseLocal(){if(!conflictRemote)return;meta={...meta,baseRevision:Number(conflictRemote.revision)||meta.baseRevision,dirty:true};saveMeta(meta);conflictRemote=null;await syncNow({forceLocal:true});}async function resolveMerge(){if(!conflictRemote)return;const merged=mergeStates(Data.getState(),conflictRemote.state);Data.restaurar(JSON.stringify(merged));observedHash=stateHash();meta={...meta,baseRevision:Number(conflictRemote.revision)||meta.baseRevision,dirty:true};saveMeta(meta);conflictRemote=null;await syncNow({forceLocal:true});document.dispatchEvent(new CustomEvent('budget:remote-applied'));}
export async function initSync(){renderSyncUI();if(!FIREBASE_SYNC.enabled)return;observedHash=stateHash();if(meta.baseRevision===0&&!meta.lastSync&&hasMeaningfulLocalData()){meta={...meta,dirty:true};saveMeta(meta);}clearInterval(observerTimer);observerTimer=setInterval(()=>{const hash=stateHash();if(hash!==observedHash){observedHash=hash;notifyLocalChange();}},900);try{const f=await loadFirebase();f.onAuthStateChanged(auth,user=>{currentUser=user;authReady=true;renderSyncUI();if(user&&navigator.onLine)syncNow().catch(showSyncError);});document.addEventListener('budget:data-changed',notifyLocalChange);window.addEventListener('online',()=>{if(currentUser)syncNow().catch(showSyncError);});}catch(e){authReady=true;renderSyncUI();showSyncError(e);}}
