/* Compatibility for historic backups; active financial calculations live elsewhere. */
import { CAPABILITIES, safeFloat, uuid } from './01_consts_utils.js';
const PERSONAL_ACCOUNT_ID='acct-personal',LEGACY_JAIMAU_ID='source-jaimau',LEGACY_UBER_ID='source-uber',LEGACY_TICKET_ID='acct-ticketcar';
const DEFAULT_PROFILE={onboarded:false,displayName:'',useCases:['personal'],transportMode:'none',capabilities:[CAPABILITIES.PERSONAL_FINANCE],currency:'MXN'};
const sourceStatus=s=>s?.status||((s?.active===false)?(s?.endedAt?'ended':'paused'):'active');
function hasMeaningfulLegacy(x){return ['turnos','movimientos','cargasCombustible','fondosCombustibleEmpresa','deudas','gastosFijosMensuales','ingresosFijos'].some(k=>Array.isArray(x?.[k])&&x[k].length>0)||Boolean(x?.parametros?.saldoInicialConfigurado)||Boolean(x?.parametros?.kmInicialConfigurado);}
export function defaultPersonalAccount(){return{id:PERSONAL_ACCOUNT_ID,name:'Caja personal',type:'cash',ownership:'personal',active:true};}
export function normalizeSource(s){const status=sourceStatus(s);return{...s,status,active:status==='active'};}
function legacySources(){return[
  {id:LEGACY_JAIMAU_ID,name:'Jaimau / Ingenico',kind:'employment',compensation:'biweekly',trackTime:true,trackDistance:true,fuelPayer:'company',fundAccountId:LEGACY_TICKET_ID,active:true,status:'active',legacyKey:'jaimau'},
  {id:LEGACY_UBER_ID,name:'Uber Eats',kind:'gig',compensation:'per_shift',trackTime:true,trackDistance:true,fuelPayer:'personal',fundAccountId:null,active:true,status:'active',legacyKey:'uber'}
];}

export function migrateFixedIncome(list){return(Array.isArray(list)?list:[]).map(f=>{if(Array.isArray(f.pagos))return{...f,pagos:f.pagos.map(p=>({...p,monto:safeFloat(p.monto)}))};const frecuencia=['Semanal','Quincenal','Mensual'].includes(f.frecuencia)?f.frecuencia:'Mensual';let pagos=[];if(frecuencia==='Semanal')pagos=[{id:uuid(),monto:0,diaSemana:String(f.diaPago||'6')}];else if(frecuencia==='Quincenal')pagos=[{id:uuid(),monto:0,diaMes:'15'},{id:uuid(),monto:0,diaMes:'fin_mes'}];else pagos=[{id:uuid(),monto:0,diaMes:String(f.diaPago||'1')}];return{...f,frecuencia,pagos};});}
export function migrateWorkSources(x){if(Array.isArray(x.workSources)&&x.workSources.length)return x.workSources.map(normalizeSource);if(!hasMeaningfulLegacy(x))return[];return legacySources();}
function legacySourceId(item){const key=item?.tipoTrabajo||item?.fuente;if(key==='jaimau')return LEGACY_JAIMAU_ID;if(key==='uber'||key==='reparto'||item?.desc==='Turno Finalizado')return LEGACY_UBER_ID;return item?.sourceId||null;}
export function migrateTurns(list,sources){return(Array.isArray(list)?list:[]).map(t=>{const sourceId=t.sourceId||legacySourceId(t),source=sources.find(s=>s.id===sourceId);return{...t,sourceId,tipoTrabajo:t.tipoTrabajo||source?.legacyKey||null,fuente:t.fuente||source?.legacyKey||sourceId,compensacion:t.compensacion||source?.compensation||'per_shift',combustible:t.combustible||source?.fuelPayer||'personal'};});}
export function migrateMovements(list){return(Array.isArray(list)?list:[]).map(m=>({...m,sourceId:m.sourceId||legacySourceId(m),accountId:m.tipo==='transferencia'?(m.accountId||null):(m.accountId||PERSONAL_ACCOUNT_ID),affectsPersonal:m.tipo==='transferencia'?false:m.affectsPersonal!==false}));}
export function migrateProfile(x,sources){if(x.profile?.onboarded!==undefined)return{...structuredClone(DEFAULT_PROFILE),...x.profile,capabilities:Array.isArray(x.profile.capabilities)?x.profile.capabilities:[CAPABILITIES.PERSONAL_FINANCE]};if(!hasMeaningfulLegacy(x))return structuredClone(DEFAULT_PROFILE);return{onboarded:true,displayName:'',useCases:['employment','gig'],transportMode:'motorcycle',capabilities:[CAPABILITIES.PERSONAL_FINANCE,CAPABILITIES.WORK,CAPABILITIES.TIME_TRACKING,CAPABILITIES.TRANSPORT,CAPABILITIES.VEHICLE,CAPABILITIES.FUEL,CAPABILITIES.THIRD_PARTY_FUNDS],currency:'MXN'};}
export function migrateAccounts(x,sources){if(Array.isArray(x.accounts)&&x.accounts.length)return x.accounts.map(a=>({...a,active:a.active!==false}));const accounts=[defaultPersonalAccount()];if(sources.some(s=>s.fuelPayer==='company'))accounts.push({id:LEGACY_TICKET_ID,name:'Fondo empresa',type:'third_party',ownership:'third_party',active:true});return accounts;}
export function normalizeBusiness(business){return{ingredients:Array.isArray(business?.ingredients)?business.ingredients:[],products:Array.isArray(business?.products)?business.products:[],sales:Array.isArray(business?.sales)?business.sales:[]};}

